name: Spring Boot Enterprise CI/CD

on:
  push:
    branches: [ "master", "dev", "security-flow" ]
  pull_request:
    branches: [ "master", "dev", "security-flow" ]

permissions:
  contents: read
  security-events: write
  id-token: write

env:
  APP_NAME: springboot-demo
  JAVA_VERSION: '17'
  MAVEN_OPTS: "-Xmx2g"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Build & Test
        run: mvn -B clean verify


  sast:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/checkout@v4

      - uses: github/codeql-action/init@v3
        with:
          languages: java

      - run: mvn -B clean package -DskipTests

      - uses: github/codeql-action/analyze@v3


  dependency-scan:
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: OWASP Dependency Check
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -DfailBuildOnCVSS=7 \
            -DskipSystemScope=true \
            -Dformats=HTML,JSON



  docker:
    runs-on: ubuntu-latest
    needs: dependency-scan

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $APP_NAME:${{ github.sha }} .


  push-image:
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password | docker login \
            --username AWS \
            --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Push Image
        run: |
          docker tag $APP_NAME:${{ github.sha }} \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:${{ github.sha }}

          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$APP_NAME:${{ github.sha }}
